version: "2"
linters:
  enable:
    - testpackage
    - gocyclo
    - revive
    - wrapcheck
    - govet
  settings:
    gocyclo:
      min-complexity: 30
    revive:
      confidence: 0.9
      rules:
        - name: indent-error-flow
        - name: import-shadowing
        - name: dot-imports
        - name: import-alias-naming
    wrapcheck:
      ignoreSigs:
        - .EOF
